name: plinko
description: "asd"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flame: ^1.16.0
  collection: ^1.18.0
  flame_audio: ^2.10.3
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  google_fonts: ^6.1.0
  animated_text_lerp: ^1.0.5
  provider: ^6.0.3
  to_csv: ^4.0.4




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/